// <auto-generated />
using System;
using Bokhandel_Labb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bokhandel_Labb.Migrations
{
    [DbContext(typeof(BokhandelContext))]
    [Migration("20251220232053_LoggHistorik2")]
    partial class LoggHistorik2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BokFörfattare", b =>
                {
                    b.Property<string>("Isbn")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("char(13)")
                        .HasColumnName("ISBN")
                        .IsFixedLength();

                    b.Property<int>("FörfattareId")
                        .HasColumnType("int")
                        .HasColumnName("FörfattareID");

                    b.HasKey("Isbn", "FörfattareId");

                    b.HasIndex("FörfattareId");

                    b.ToTable("BokFörfattare", (string)null);
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.Butiker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Butiksnamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Postnummer")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .IsFixedLength();

                    b.Property<string>("Stad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Butiker__3214EC27B7B476AB");

                    b.ToTable("Butiker", (string)null);
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.Böcker", b =>
                {
                    b.Property<string>("Isbn")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("char(13)")
                        .HasColumnName("ISBN")
                        .IsFixedLength();

                    b.Property<int?>("FörlagId")
                        .HasColumnType("int")
                        .HasColumnName("FörlagID");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int")
                        .HasColumnName("KategoriID");

                    b.Property<decimal>("Pris")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("Sidantal")
                        .HasColumnType("int");

                    b.Property<string>("Språk")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("Utgivningsdatum")
                        .HasColumnType("date");

                    b.HasKey("Isbn")
                        .HasName("PK_Böcker_ISBN");

                    b.HasIndex("FörlagId");

                    b.HasIndex("KategoriId");

                    b.ToTable("Böcker", (string)null);
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.Författare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Efternamn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("Födelsedatum")
                        .HasColumnType("date");

                    b.Property<string>("Förnamn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Författa__3214EC2725F35BCA");

                    b.ToTable("Författare", (string)null);
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.Förlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Grundat")
                        .HasColumnType("int");

                    b.Property<string>("Land")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Webbplats")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Förlag__3214EC27C41A285E");

                    b.ToTable("Förlag", (string)null);
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.FörsäljningPerButik", b =>
                {
                    b.Property<int?>("AntalOrdrar")
                        .HasColumnType("int")
                        .HasColumnName("Antal Ordrar");

                    b.Property<int?>("AntalUnikaKunder")
                        .HasColumnType("int")
                        .HasColumnName("Antal Unika Kunder");

                    b.Property<string>("Butiksnamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MedianOrdervärde")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("Median Ordervärde");

                    b.Property<string>("Stad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalOmsättning")
                        .HasColumnType("decimal(38, 2)")
                        .HasColumnName("Total Omsättning");

                    b.ToTable((string)null);

                    b.ToView("FörsäljningPerButik", (string)null);
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.Kategorier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beskrivning")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Kategori__3214EC27097C1965");

                    b.HasIndex(new[] { "Namn" }, "UQ__Kategori__737584FD56687B9C")
                        .IsUnique();

                    b.ToTable("Kategorier", (string)null);
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.Kunder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Efternamn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Förnamn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Postnummer")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .IsFixedLength();

                    b.Property<DateOnly>("Registreringsdatum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Stad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Kunder__3214EC274C6CF72A");

                    b.HasIndex(new[] { "Email" }, "UQ__Kunder__A9D10534E0A6C92C")
                        .IsUnique();

                    b.ToTable("Kunder", (string)null);
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.LagerSaldo", b =>
                {
                    b.Property<int>("ButikId")
                        .HasColumnType("int")
                        .HasColumnName("ButikID");

                    b.Property<string>("Isbn")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("char(13)")
                        .HasColumnName("ISBN")
                        .IsFixedLength();

                    b.Property<int>("Antal")
                        .HasColumnType("int");

                    b.HasKey("ButikId", "Isbn");

                    b.HasIndex("Isbn");

                    b.ToTable("LagerSaldo", (string)null);
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.LagersaldoPerButik", b =>
                {
                    b.Property<string>("AkademibokhandelnGöteborg")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Akademibokhandeln Göteborg");

                    b.Property<string>("BokhandelnStockholmCity")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Bokhandeln Stockholm City");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("char(13)")
                        .HasColumnName("ISBN")
                        .IsFixedLength();

                    b.Property<string>("StudentbokhandelnMalmö")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Studentbokhandeln Malmö");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.ToTable((string)null);

                    b.ToView("LagersaldoPerButik", (string)null);
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.LoggHistorik", b =>
                {
                    b.Property<int>("LoggId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LoggId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoggId"));

                    b.Property<int>("ButikId")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<string>("Butiksnamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime");

                    b.Property<string>("Händelse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasKey("LoggId");

                    b.ToTable("LoggHistorik", (string)null);
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.OrderRader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Antal")
                        .HasColumnType("int");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("char(13)")
                        .HasColumnName("ISBN")
                        .IsFixedLength();

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<decimal>("Pris")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__OrderRad__3214EC27F072A007");

                    b.HasIndex("Isbn");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderRader", (string)null);
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.Ordrar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ButikId")
                        .HasColumnType("int")
                        .HasColumnName("ButikID");

                    b.Property<int>("KundId")
                        .HasColumnType("int")
                        .HasColumnName("KundID");

                    b.Property<DateTime>("Orderdatum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pågående");

                    b.Property<decimal>("TotalBelopp")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Ordrar__3214EC27C5DA7BF8");

                    b.HasIndex("ButikId");

                    b.HasIndex("KundId");

                    b.ToTable("Ordrar", (string)null);
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.TitlarPerFörfattare", b =>
                {
                    b.Property<string>("Lagervärde")
                        .IsRequired()
                        .HasMaxLength(44)
                        .IsUnicode(false)
                        .HasColumnType("varchar(44)");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasMaxLength(101)
                        .HasColumnType("nvarchar(101)");

                    b.Property<string>("Titlar")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Ålder")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.ToTable((string)null);

                    b.ToView("TitlarPerFörfattare", (string)null);
                });

            modelBuilder.Entity("BokFörfattare", b =>
                {
                    b.HasOne("Bokhandel_Labb.Models.Författare", null)
                        .WithMany()
                        .HasForeignKey("FörfattareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BokFörfattare_Författare");

                    b.HasOne("Bokhandel_Labb.Models.Böcker", null)
                        .WithMany()
                        .HasForeignKey("Isbn")
                        .IsRequired()
                        .HasConstraintName("FK_BokFörfattare_Böcker");
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.Böcker", b =>
                {
                    b.HasOne("Bokhandel_Labb.Models.Förlag", "Förlag")
                        .WithMany("Böckers")
                        .HasForeignKey("FörlagId")
                        .HasConstraintName("FK_Böcker_Förlag");

                    b.HasOne("Bokhandel_Labb.Models.Kategorier", "Kategori")
                        .WithMany("Böckers")
                        .HasForeignKey("KategoriId")
                        .HasConstraintName("FK_Böcker_Kategorier");

                    b.Navigation("Förlag");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.LagerSaldo", b =>
                {
                    b.HasOne("Bokhandel_Labb.Models.Butiker", "Butik")
                        .WithMany("LagerSaldos")
                        .HasForeignKey("ButikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LagerSaldo_Butiker");

                    b.HasOne("Bokhandel_Labb.Models.Böcker", "IsbnNavigation")
                        .WithMany("LagerSaldos")
                        .HasForeignKey("Isbn")
                        .IsRequired()
                        .HasConstraintName("FK_LagerSaldo_Böcker");

                    b.Navigation("Butik");

                    b.Navigation("IsbnNavigation");
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.OrderRader", b =>
                {
                    b.HasOne("Bokhandel_Labb.Models.Böcker", "IsbnNavigation")
                        .WithMany("OrderRaders")
                        .HasForeignKey("Isbn")
                        .IsRequired()
                        .HasConstraintName("FK_OrderRader_Böcker");

                    b.HasOne("Bokhandel_Labb.Models.Ordrar", "Order")
                        .WithMany("OrderRaders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderRader_Ordrar");

                    b.Navigation("IsbnNavigation");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.Ordrar", b =>
                {
                    b.HasOne("Bokhandel_Labb.Models.Butiker", "Butik")
                        .WithMany("Ordrars")
                        .HasForeignKey("ButikId")
                        .IsRequired()
                        .HasConstraintName("FK_Ordrar_Butiker");

                    b.HasOne("Bokhandel_Labb.Models.Kunder", "Kund")
                        .WithMany("Ordrars")
                        .HasForeignKey("KundId")
                        .IsRequired()
                        .HasConstraintName("FK_Ordrar_Kunder");

                    b.Navigation("Butik");

                    b.Navigation("Kund");
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.Butiker", b =>
                {
                    b.Navigation("LagerSaldos");

                    b.Navigation("Ordrars");
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.Böcker", b =>
                {
                    b.Navigation("LagerSaldos");

                    b.Navigation("OrderRaders");
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.Förlag", b =>
                {
                    b.Navigation("Böckers");
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.Kategorier", b =>
                {
                    b.Navigation("Böckers");
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.Kunder", b =>
                {
                    b.Navigation("Ordrars");
                });

            modelBuilder.Entity("Bokhandel_Labb.Models.Ordrar", b =>
                {
                    b.Navigation("OrderRaders");
                });
#pragma warning restore 612, 618
        }
    }
}
